### ISSUE TITLE
Attempted to load class "PretrainedModel" in Symfony 5

### ISSUE THREAD

**Issue by tuanla-kiai** [CodeWithKyrian/transformers-php#3]
### System Info

Symfony 5

### PHP Version

8.1.27

### Environment/Platform

- [ ] Command-line application
- [X] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

Hi, I get an error, please help me.
![image](https://github.com/CodeWithKyrian/transformers-php/assets/112920872/18d3b6e2-6f1c-48b0-9b57-2edc3abfba55)

### Reproduction

```php
        $fillMask = pipeline('fill-mask');

        $result = $fillMask('The quick brown <mask> jumps over the lazy dog.');
```

**Comment by CodeWithKyrian** [comment]
Thanks for bringing this to my attention. I just noticed the slight discrepancy between the naming (uppercase T in some places, and lowercase in others) - `PreTrainedModel` and `PretrainedModel`. For MacOSX, which I'm using for development,  `vim File` and `vim file` are the same, so it will work with no problem. I guess that's why it slipped through my fingers. I'll fix it right away

**Comment by CodeWithKyrian** [comment]
Fixed in https://github.com/CodeWithKyrian/transformers-php/pull/4. Update to v0.2.0 to access the changes

**Comment by tuanla-kiai** [comment]
@CodeWithKyrian Same error with WordpieceTokenizer in Tokenizer file (line 64), please update it 🚀

**Comment by CodeWithKyrian** [comment]
Thanks for that. Update to v0.2.1 to access the fixes
