### ISSUE TITLE
Image::thumbnail type error

### ISSUE THREAD

**Issue by k99k5** [CodeWithKyrian/transformers-php#57]
### System Info

-

### PHP Version

8.3

### Environment/Platform

- [X] Command-line application
- [ ] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

```
PHP Fatal error:  Uncaught TypeError: Codewithkyrian\Transformers\Utils\Image::resize(): Argument #1 ($width) must be of type int, float given, called in \vendor\codewithkyrian\transformers\src\Utils\Image.php on line 168 and defined in \vendor\codewithkyrian\transformers\src\Utils\Image.php:136
Stack trace:
#0 \vendor\codewithkyrian\transformers\src\Utils\Image.php(168): Codewithkyrian\Transformers\Utils\Image->resize(768.0, 1024, 2)
```

### Reproduction

-

**Comment by CodeWithKyrian** [comment]
The error you’re encountering is due to the type constraint in the `thumbnail()` method, which expects the width and height to be integers. It's an intentional design choice, as image dimensions are typically whole numbers across most image processing software, both commercial and open source.

Allowing floats could lead to unintended behavior or inaccuracies in image processing. To resolve this, I recommend rounding and casting your values to integers before passing them to the `thumbnail()` or `resize()` methods, especially if you’re calculating dimensions dynamically.

```php
$width = (int) round($yourCalculatedWidth);
$height = (int) round($yourCalculatedHeight);

$image->thumbnail($width, $height);
```

**Comment by k99k5** [comment]
The `floor` returned in the `thumbnail` method is of type `float`.



---Original---
From: "Kyrian ***@***.***&gt;
Date: Fri, Aug 16, 2024 11:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CodeWithKyrian/transformers-php] Image::thumbnail type error(Issue #57)




 
The error you’re encountering is due to the type constraint in the thumbnail() method, which expects the width and height to be integers. It's an intentional design choice, as image dimensions are typically whole numbers across most image processing software, both commercial and open source.
 
Allowing floats could lead to unintended behavior or inaccuracies in image processing. To resolve this, I recommend rounding and casting your values to integers before passing them to the thumbnail() or resize() methods, especially if you’re calculating dimensions dynamically.
 $width = (int) round($yourCalculatedWidth); $height = (int) round($yourCalculatedHeight); $image-&gt;thumbnail($width, $height);
